---
title: "Beams"
author: "Zepeng (Phoenix) Mu"
date: "3/1/2018"
output:
  pdf_document: default
  html_document: default
---

### Set constants for plot
```{r}
myWidth = 5
number_of_points = 50

x0 = rep(-2, number_of_points)
y0 = rep(0, number_of_points)

xFixed = sin(seq(-myWidth, myWidth, length.out = number_of_points))
yFixed = cos(seq(-myWidth, myWidth, length.out = number_of_points))
```

### The more randomness, the more fun
```{r}
xRandom = xFixed + rnorm(number_of_points, mean = 0.6, sd = 2)
yRandom = yFixed + rnorm(number_of_points, mean = 0, sd = 2)
myLwd = rnorm(number_of_points, mean = 1.3, sd = 0.3)
myLty = sample(c(1, 2, 3), number_of_points, replace = T)
```

### Get beautiful random colors
```{r set color}
red = sample(seq(0.4, 1, 0.1), number_of_points, replace = T)
green = sample(seq(0, 0.5, 0.1), number_of_points, replace = T)
blue = sample(seq(0, 1, 0.1), number_of_points, replace = T)
```

Now we can generate the plot.
```{r fig.height=6, fig.width=10}
# Plot
mypar = par(bg = 'black', mar = rep(0.5, 4))
plot.new()
plot.window(xlim = c(-myWidth, myWidth), ylim = c(-myWidth, myWidth), asp = 1)
segments(x0, y0, xRandom, yRandom,
         lwd = myLwd,
         col = rgb(red, green, blue))
# signature
legend("bottomright", legend="© Phoenix", bty = "n", text.col="gray70")


```